#!/usr/bin/env ruby

def fasta_to_hash(infile)
  f=File.open(infile,"r")
  return_hash = {}
  name = ""
  while line = f.gets do
    if line =~ /^\>/
      name = line.chomp
      return_hash[name] = ""
    else
      return_hash[name] += line.chomp
    end
  end
  f.close
  return return_hash
end

number = 100

infile = ARGV[0]

number = ARGV[1].to_i if ARGV[1]

seq = fasta_to_hash(infile)
out_seq = {}
seq.keys.sample(number).each do |name|
  out_seq[name] = seq[name][0..-1]
end

outfile = File.dirname(infile) + "/" + File.basename(infile,".*") + "_" + number.to_s

out = File.open(outfile,"w")

out_seq.each do |k,v|
  out.puts k
  out.puts v
end
